FROM python:3.10.6-alpine3.16
LABEL maintainer = "SharukhAtar"
WORKDIR /usr/src/pythoncodes

COPY add_two_numbers.py /usr/src/pythoncodes
CMD ["python3","add_two_numbers.py"]

# docker build -t addtwonumber:v0 .
# docker run -it addtwonumber:v0
# sudo docker run --name addcal -it addtwonumber:v0
