FROM ubuntu:18.04
#RUN instruction
LABEL maintainer="SharukhAtar"
RUN apt update && apt install net-tools -y && apt install python3 -y
CMD ["echo ","How to run instruction inside docker"]

# sudo docker build -t diotos:v2 .
# sudo docker run -it diotos:v2
# sudo docker run  -it diotos:v2 bash
# sudo docker images
# docker inspect <imagename>---details about image